function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Odd_Even"};
	this.sidHashMap["Odd_Even"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Odd_Even:19"};
	this.sidHashMap["Odd_Even:19"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Odd_Even:5"};
	this.sidHashMap["Odd_Even:5"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S3>"] = {sid: "Odd_Even:10"};
	this.sidHashMap["Odd_Even:10"] = {rtwname: "<S3>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "Odd_Even:1"};
	this.sidHashMap["Odd_Even:1"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Subsystem"] = {sid: "Odd_Even:19"};
	this.sidHashMap["Odd_Even:19"] = {rtwname: "<Root>/Subsystem"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "Odd_Even:16"};
	this.sidHashMap["Odd_Even:16"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "Odd_Even:20"};
	this.sidHashMap["Odd_Even:20"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "Odd_Even:3"};
	this.sidHashMap["Odd_Even:3"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/If"] = {sid: "Odd_Even:4"};
	this.sidHashMap["Odd_Even:4"] = {rtwname: "<S1>/If"};
	this.rtwnameHashMap["<S1>/If Action Subsystem"] = {sid: "Odd_Even:5"};
	this.sidHashMap["Odd_Even:5"] = {rtwname: "<S1>/If Action Subsystem"};
	this.rtwnameHashMap["<S1>/If Action Subsystem1"] = {sid: "Odd_Even:10"};
	this.sidHashMap["Odd_Even:10"] = {rtwname: "<S1>/If Action Subsystem1"};
	this.rtwnameHashMap["<S1>/Merge"] = {sid: "Odd_Even:15"};
	this.sidHashMap["Odd_Even:15"] = {rtwname: "<S1>/Merge"};
	this.rtwnameHashMap["<S1>/Rem"] = {sid: "Odd_Even:2"};
	this.sidHashMap["Odd_Even:2"] = {rtwname: "<S1>/Rem"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "Odd_Even:21"};
	this.sidHashMap["Odd_Even:21"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/Action Port"] = {sid: "Odd_Even:7"};
	this.sidHashMap["Odd_Even:7"] = {rtwname: "<S2>/Action Port"};
	this.rtwnameHashMap["<S2>/String Constant"] = {sid: "Odd_Even:9"};
	this.sidHashMap["Odd_Even:9"] = {rtwname: "<S2>/String Constant"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "Odd_Even:8"};
	this.sidHashMap["Odd_Even:8"] = {rtwname: "<S2>/Out1"};
	this.rtwnameHashMap["<S3>/Action Port"] = {sid: "Odd_Even:12"};
	this.sidHashMap["Odd_Even:12"] = {rtwname: "<S3>/Action Port"};
	this.rtwnameHashMap["<S3>/String Constant"] = {sid: "Odd_Even:14"};
	this.sidHashMap["Odd_Even:14"] = {rtwname: "<S3>/String Constant"};
	this.rtwnameHashMap["<S3>/Out1"] = {sid: "Odd_Even:13"};
	this.sidHashMap["Odd_Even:13"] = {rtwname: "<S3>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
