function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Factorial_ForLoop"};
	this.sidHashMap["Factorial_ForLoop"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Factorial_ForLoop:2"};
	this.sidHashMap["Factorial_ForLoop:2"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Factorial_ForLoop:15"};
	this.sidHashMap["Factorial_ForLoop:15"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "Factorial_ForLoop:1"};
	this.sidHashMap["Factorial_ForLoop:1"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "Factorial_ForLoop:31"};
	this.sidHashMap["Factorial_ForLoop:31"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Display"] = {sid: "Factorial_ForLoop:28"};
	this.sidHashMap["Factorial_ForLoop:28"] = {rtwname: "<Root>/Display"};
	this.rtwnameHashMap["<Root>/For Iterator Subsystem"] = {sid: "Factorial_ForLoop:2"};
	this.sidHashMap["Factorial_ForLoop:2"] = {rtwname: "<Root>/For Iterator Subsystem"};
	this.rtwnameHashMap["<Root>/For Iterator Subsystem1"] = {sid: "Factorial_ForLoop:15"};
	this.sidHashMap["Factorial_ForLoop:15"] = {rtwname: "<Root>/For Iterator Subsystem1"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "Factorial_ForLoop:21"};
	this.sidHashMap["Factorial_ForLoop:21"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "Factorial_ForLoop:3"};
	this.sidHashMap["Factorial_ForLoop:3"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/For Iterator"] = {sid: "Factorial_ForLoop:7"};
	this.sidHashMap["Factorial_ForLoop:7"] = {rtwname: "<S1>/For Iterator"};
	this.rtwnameHashMap["<S1>/Product"] = {sid: "Factorial_ForLoop:8"};
	this.sidHashMap["Factorial_ForLoop:8"] = {rtwname: "<S1>/Product"};
	this.rtwnameHashMap["<S1>/Unit Delay"] = {sid: "Factorial_ForLoop:9"};
	this.sidHashMap["Factorial_ForLoop:9"] = {rtwname: "<S1>/Unit Delay"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "Factorial_ForLoop:5"};
	this.sidHashMap["Factorial_ForLoop:5"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/In1"] = {sid: "Factorial_ForLoop:32"};
	this.sidHashMap["Factorial_ForLoop:32"] = {rtwname: "<S2>/In1"};
	this.rtwnameHashMap["<S2>/For Iterator"] = {sid: "Factorial_ForLoop:17"};
	this.sidHashMap["Factorial_ForLoop:17"] = {rtwname: "<S2>/For Iterator"};
	this.rtwnameHashMap["<S2>/Product"] = {sid: "Factorial_ForLoop:19"};
	this.sidHashMap["Factorial_ForLoop:19"] = {rtwname: "<S2>/Product"};
	this.rtwnameHashMap["<S2>/Unit Delay"] = {sid: "Factorial_ForLoop:20"};
	this.sidHashMap["Factorial_ForLoop:20"] = {rtwname: "<S2>/Unit Delay"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "Factorial_ForLoop:29"};
	this.sidHashMap["Factorial_ForLoop:29"] = {rtwname: "<S2>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
